### ISSUE TITLE
Suggestion: Don't insert a literal Tab character when tab-completion finds no possible completions

### ISSUE THREAD

**Issue by mklement0** [ironmansoftware/psedit#60]
Currently, when you, say, mistype the start of a command and attempt tab-completion in vain, a literal tab character is inserted.

Following the model of PSReadLine, I think it would be more helpful for such a tab-completion attempt to be a _no-op_.

E.g., typing `Gett-C` and pressing <kbd>Tab</kbd> should be a no-op rather than inserting a tab character.

**Comment by halvarsson** [comment]
This is happening cause the autocomplete is no longer active, and our editor allows for normal tabs to be inserted

I think supporting tabs causes way more problems than it solves, since the auto formatter is anyways replacing tabs with spaces etc.

I have disabled tabs by default now, and the behavior can be re-enabled from the "Format" menu
This solves the problem described in this issue :)

**Comment by mklement0** [comment]
Thanks, @halvarsson.
